spring.application.name=CarRentalWeb
server.port=5000

spring.datasource.url=jdbc:mysql://localhost:3306/carrentalweb?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=quockiet3304@gmail.com
spring.mail.password=cklfbjtjpaitjmqb
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

